"'Product Screen' As screen":
    Fill: =RGBA(29, 29, 29, 1)
    LoadingSpinnerColor: =RGBA(100, 118, 132, 1)

    "Gallery2 As gallery.'BrowseLayout_Horizontal_TwoTextOneImageVariant_ver4.0'":
        BorderColor: =RGBA(197, 203, 207, 1)
        Items: =Products
        TemplatePadding: =0
        TemplateSize: =Min(440, Self.Height - 60)
        Width: =1192
        X: =40
        Y: =40
        ZIndex: =1

        Image4 As image:
            BorderColor: =RGBA(197, 203, 207, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledFill: =RGBA(244, 244, 244, 1)
            Height: =276
            Image: =ThisItem.'Product Image'
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth - 32
            X: =(Parent.TemplateWidth / 2) - (Self.Width / 2)
            Y: =16
            ZIndex: =1

        Title2 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FontWeight: =FontWeight.Semibold
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =20
            Text: =ThisItem.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.TemplateWidth - 64
            X: =32
            Y: =Image4.Y + Image4.Height + 16
            ZIndex: =2

        Subtitle2 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =18
            Text: ="$" & Text(ThisItem.'Price',"0.00")
            VerticalAlign: =VerticalAlign.Top
            Width: =Title2.Width
            X: =Title2.X
            Y: =Title2.Y + Title2.Height + 8
            ZIndex: =3

